sudo: false
language: node_js
node_js:
  - "13.0.1"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
after_success:
- bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
install:
- npm install
script:
- npm test
- npm run lint
- npm run report-coverage